name: Deploy Spring Boot to Azure App Service
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          ./mvnw clean package
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: my-backend
          resource-group: my-app-resource-group
          package: backend/target/*.jar
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
